version: '2.4'

services:
  honey-pot:
    container_name: honey-pot
    build:
      context: .
      dockerfile: HoneyPot.Api/Dockerfile
    ports:
      - "4242:80"
    environment:
      - "HoneyPotServiceOptions__PollingIntervalInMinutes=6"
    networks:
      - local

  redis:
    image: "redis:6.0.9-alpine"
    container_name: redis
    command: redis-server
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    #volumes:
    #  - ./redis-data:/var/lib/redis
    #  - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - local

networks:
  local:
    name: local